name: Mining
version: '${project.version}'
main: com.github.zululi.mining.Mining
api-version: 1.19
author: zululi

commands:
  start:
    description: start mining battle

  team-auto-warifuri:
    description: team warifuri

  team-red-warifuri:
    description: redteam warifuri

  team-blue-warifuri:
    description: blueteam warifuri

  team-empty:
    description: team empty

  quick-start:
      description: quick start

  set-time:
    description: time set